import Head from "next/head";
import Image from "next/image";
import { useState, useEffect } from "react";
import { AiOutlineMenu } from "react-icons/ai";
import Intro from "../components/Intro";
import DropDown from "../components/DropDown";
import About from "../components/About";
import Skills from "../components/Skills";
import Projects from "../components/project/Projects";
import Contact from "../components/Contact";
import Social from "../components/Social";

import Slide from "react-reveal/Slide";

export default function Home() {
	const [visible, setVisible] = useState(true);
	const [openSideBar, setOpenSideBar] = useState(false);

	const handleScroll = () => {
		if (window.scrollY > 100) {
			setVisible(false);
		} else {
			setVisible(true);
		}
	};

	useEffect(() => {
		window.addEventListener("scroll", handleScroll);

		return () => window.removeEventListener("scroll", handleScroll);
	}, []);

	return (
		<div className='font-sans overflow-y-hidden bg-[#001a1a] z-20'>
			<Head>
				<title>Valentine Chinedu</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' sizes='64x64' />
			</Head>

			<header className='relative h-screen'>
				<nav
					className={`fixed flex justify-between items-center z-40 w-full px-6 transition-height ease-in-out duration-500 overflow-hidden bg-[#083f3f] bg-opacity-20 ${
						visible ? "h-[4.5rem]" : "h-0"
					}`}
				>
					<div className='flex '>
						<Image
							src='/logo_transparent.png'
							alt='logo'
							width={64}
							height={64}
							responsive
						/>
					</div>
					<div
						onClick={() => {
							setOpenSideBar(true);
						}}
						className='relative left-1 '
					>
						<AiOutlineMenu className='text-4xl text-[#00ffff]' />
					</div>
				</nav>
				<DropDown openSideBar={openSideBar} setOpenSideBar={setOpenSideBar} />
				<Intro openSideBar={openSideBar} />
			</header>

			{/* close sidebar on screen touch/click */}
			{openSideBar && (
				<div
					onClick={() => {
						setOpenSideBar(false);
					}}
					className='fixed h-full inset-0 z-40'
				></div>
			)}

			{/* Side menu button */}
			<div
				onClick={() => {
					setOpenSideBar(true);
				}}
				className={`fixed z-40 bottom-8 right-5 bg-gray-200 p-1 bg-opacity-10 ${
					visible ? "invisible" : ""
				}`}
			>
				<AiOutlineMenu className='text-3xl md:text-4xl text-[#00ffff]' />
			</div>

			<main className={`${openSideBar ? "filter blur-sm" : ""}`}>
				<About openSideBar={openSideBar} />
				<Skills openSideBar={openSideBar} />
				<Projects openSideBar={openSideBar} />
			</main>
			<footer className={`${openSideBar ? "filter blur-sm" : ""}`}>
				<Slide bottom duration={1000}>
					<Contact />
					<div className='flex w-full justify-center text-gray-400 mb-6 text-sm'>
						<p>Built with Nextjs and Talwindcss</p>
					</div>
					<Social />
					<div className='flex w-full justify-center text-sm text-gray-400 mb-4 md:mb-8'>
						<p>Design inspired by Brittany Chiang</p>
					</div>
				</Slide>
			</footer>
		</div>
	);
}
