import Head from "next/head";
import Image from "next/image";
import { useState, useEffect } from "react";
import { AiOutlineMenu } from "react-icons/ai";
import Intro from "../components/Intro";
import SideMenu from "../components/SideMenu";
import About from "../components/About";
import Skills from "../components/skill/Skills";
import Projects from "../components/project/Projects";
import Contact from "../components/Contact";
import Social from "../components/Social";

import Slide from "react-reveal/Slide";

export default function Home() {
	const [visible, setVisible] = useState(true);
	const [openSideBar, setOpenSideBar] = useState(false);

	const handleScroll = () => {
		if (window.scrollY > 100) {
			setVisible(false);
		} else {
			setVisible(true);
		}
	};

	useEffect(() => {
		window.addEventListener("scroll", handleScroll);

		return () => window.removeEventListener("scroll", handleScroll);
	}, []);

	return (
		<div className='font-sans overflow-hidden bg-[#100020] z-20 h-full w-full '>
			<Head>
				<title>Valentine Chinedu</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' sizes='64x64' />
			</Head>

			<header className='h-screen w-full'>
				<nav
					className={`fixed flex justify-between items-center z-40 w-full px-6 transition-height ease-in-out duration-500 overflow-hidden bg-gray-700 bg-opacity-20 lg:bg-opacity-100 lg:h-[4.5rem] ${
						visible ? "h-[4.5rem]" : "h-0"
					}`}
				>
					<div className='flex '>
						<Image
							src='/logo_transparent.png'
							alt='logo'
							width={64}
							height={64}
							responsive='true'
						/>
					</div>
					<div className='hidden lg:flex h-full justify-around w-[35rem] text-sm'>
						<a href='#about' className='flex items-center space-x-1 group'>
							<p className='text-[#00ffff] font-medium'>01.</p>
							<h2 className='text-gray-200 font-semibold tracking-wider group-hover:border-b border-[#00ffff]'>
								About
							</h2>
						</a>
						<a href='#skills' className='flex items-center space-x-1 group'>
							<p className='text-[#00ffff] font-medium'>02.</p>
							<h2 className='text-gray-200 font-semibold tracking-wider group-hover:border-b border-[#00ffff]'>
								Skills
							</h2>
						</a>
						<a href='#projects' className='flex items-center space-x-1 group'>
							<p className='text-[#00ffff] font-medium'>03.</p>
							<h2 className='text-gray-200 font-semibold tracking-wider group-hover:border-b border-[#00ffff] '>
								Projects
							</h2>
						</a>
						<a href='#contact' className='flex items-center space-x-1 group'>
							<p className='text-[#00ffff] font-medium'>04.</p>
							<h2 className='text-gray-200 font-semibold tracking-wider group-hover:border-b border-[#00ffff] '>
								Contact
							</h2>
						</a>
						<div className='flex items-center'>
							<button className=' border-solid border border-[#00ffff] text-[#00ffff] hover:bg-[#00ffff] hover:bg-opacity-20 rounded px-4 py-2 font-semibold focus:outline-none'>
								Resume
							</button>
						</div>
					</div>
					<div
						onClick={() => {
							setOpenSideBar(true);
						}}
						className='lg:hidden relative left-1 '
					>
						<AiOutlineMenu className='text-4xl text-[#00ffff]' />
					</div>
				</nav>
				<SideMenu openSideBar={openSideBar} setOpenSideBar={setOpenSideBar} />
				<Intro openSideBar={openSideBar} />
			</header>

			{/* close sidebar on screen touch/click */}
			{openSideBar && (
				<div
					onClick={() => {
						setOpenSideBar(false);
					}}
					className='fixed h-full inset-0 z-40'
				></div>
			)}

			{/* Side menu button */}
			<div
				onClick={() => {
					setOpenSideBar(true);
				}}
				className={`lg:hidden fixed z-40 bottom-8 right-5 bg-gray-200 p-1 bg-opacity-10 ${
					visible ? "invisible" : ""
				}`}
			>
				<AiOutlineMenu className='text-3xl md:text-4xl text-[#00ffff]' />
			</div>

			<main className={`${openSideBar ? "filter blur-sm" : ""}`}>
				<Slide bottom duration={1000}>
					<About openSideBar={openSideBar} />
					<Skills openSideBar={openSideBar} />
					<Projects openSideBar={openSideBar} />
				</Slide>
			</main>
			<footer
				className={`lg:container lg:mx-auto lg:px-80 lg:pt-4 ${
					openSideBar ? "filter blur-sm" : ""
				}`}
			>
				<Contact />
				<div className='flex w-full justify-center text-gray-300 mb-6 lg:mb-4 text-sm'>
					<p>Built with Nextjs and Tailwindcss</p>
				</div>
				<Social />
				<div className='flex w-full justify-center text-sm text-gray-300 mb-4 md:mb-8'>
					<p>Design inspired by Brittany Chiang</p>
				</div>
			</footer>
		</div>
	);
}
