import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { AiOutlineMenu } from "react-icons/ai";
import DropDown from "../components/DropDown";

export default function Home() {
	const [openSideBar, setOpenSideBar] = useState(false);
	return (
		<div className='font-serif'>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<header className='relative h-screen'>
				<nav className='fixed flex justify-between items-center w-full px-6 pt-4 bg-[#09143b] h-[4.5rem]'>
					<div>logo</div>
					<div
						onClick={() => {
							setOpenSideBar(true);
						}}
						className='h-full'
					>
						<AiOutlineMenu className='text-4xl text-green-200' />
					</div>
				</nav>
				<DropDown openSideBar={openSideBar} setOpenSideBar={setOpenSideBar} />
			</header>
		</div>
	);
}
